import csv, idna
from pathlib import Path

DOMAINS = Path("data/domains.csv")
ALLOW = Path("data/allowlist.csv")
OUT = Path("build/disavow.txt")

def normalize(domain: str) -> str:
    d = domain.strip().lower().split('/')[0]
    if d.startswith("www."):
        d = d[4:]
    return idna.encode(d).decode("ascii")

def load_allowlist():
    allow = set()
    if ALLOW.exists():
        with ALLOW.open(encoding="utf-8") as f:
            for row in csv.DictReader(f):
                allow.add(normalize(row["domain"]))
    return allow

def main():
    allow = load_allowlist()
    seen = set()
    lines = ["# Auto-generated by OpenDisavow", "# Review before uploading to GSC", ""]

    with DOMAINS.open(encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            raw = row.get("domain", "")
            if not raw:
                continue
            try:
                d = normalize(raw)
            except Exception:
                # Skip invalid IDN or malformed domains
                continue
            if d in allow or d in seen:
                continue
            lines.append(f"domain: {d}")
            seen.add(d)

    OUT.parent.mkdir(exist_ok=True, parents=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"✅ Generated {len(seen)} domains -> {OUT}")

if __name__ == "__main__":
    main()
